services:
  - type: web
    name: laravel-mongodb-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:J1CoMTbkXdQ/TQFnFlJkAcSrs4UGQdqohPvkvj2KFRY=
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        value: mongodb+srv://muhammedsuhailkm2003:Sunu7861@cluster0.iaazwrn.mongodb.net/?appName=Cluster0
      - key: DB_DATABASE
        value: blog
